# Generated by Django 3.2.25 on 2025-03-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfigurationCrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdminConfigurationFarmType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminconfigurations.adminconfigurationcrop')),
                ('farm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminconfigurations.adminconfigurationfarmtype')),
            ],
        ),
    ]
